### ISSUE TITLE
Search_Formaldehyde_Cross-links is not working for me.

### ISSUE THREAD

**Issue by WeiqiangChen** [Kalisman-Lab/Search_Formaldehyde_Cross-links#1]
I loaded fasta file and mgf file and got the following log in the exported result.

Log: Loading FASTA file: D:/.../combined.fasta  ...  
Log: Loaded 19135 sequences.
Log: No decoy sequences.   Done.
Log: Protease is: Trypsin. Number of allowed miscleavages: 2
Log: 2746664 peptides created without modifications.
Log: 2746664 peptides in total with modifications.
Log: Loading MGF file: D:/..../InSol_SDC_200ppm_FA_95deg_10p.mgf  ...  
Exception in thread "main" java.util.NoSuchElementException
	at java.base/java.util.StringTokenizer.nextToken(StringTokenizer.java:349)
	at findXL.MSdata.readMGFfile(MSdata.java:55)
	at findXL.MSdata.<init>(MSdata.java:23)
	at findXL.RunTest.main(RunTest.java:28)

Could you please help me to make it run?

**Comment by enriquead1** [comment]
Exactly the same is happening to me, did you find out how to solve it?

**Comment by Kalisman-Lab** [comment]
Currently, the application can only work with MGF files that were generated by Thermo's Proteteome Discoverer. Conversions to MGFs by other applications result in slightly different formats that the Formaldehyde Analyzer cannot read correctly. My guess is that the inability of the application to read the MGF file stems from this issue.
Sorry for the inconvenience,
Nir
